spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/track
    username: track
    password: track
  
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.track: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

